# Generated by Django 4.0.6 on 2022-07-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('season', models.IntegerField()),
                ('year', models.IntegerField()),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
