# Generated by Django 4.0.6 on 2022-07-17 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_performer_alter_review_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performer',
            old_name='age',
            new_name='born_year',
        ),
    ]
