# Generated by Django 4.0.6 on 2022-07-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_age_performer_born_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='performers',
            field=models.ManyToManyField(to='main_app.performer'),
        ),
    ]
